[theme]
base = "light"
primaryColor = "#FAD32B"
backgroundColor = "#F9FAFB"            # cinza bem claro
secondaryBackgroundColor = "#F3F4F6"   # cartões/sidebar
textColor = "#111827"                  # cinza quase preto
font = "sans serif"

[theme]
base = "dark"
primaryColor = "#FAD32B"
backgroundColor = "#0E1117"            # fundo escuro
secondaryBackgroundColor = "#1A1B26"   # cartões/sidebar
textColor = "#E5E7EB"                  # texto claro
font = "sans serif"


